# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9988086a72b8b8d8e546b19f065c03f3aed0d59fa2d36dc96a877dd31a2e3547eac779c7a0fb97e43fbb5a3bac2b385ea3676cbf2aba557d28d8dacb2e13be0

test:
  secret_key_base: d4ff0c677252bd24725ce8f1962337c6ad8516a8281dbe5664aec022bd0a81d2df667d8812f231123fc130b8e88569df457826946dfc02d21ad38e68af5dae91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
